### ISSUE TITLE
couldn't open "Images/pencil_tool.gif"

### ISSUE THREAD

**Issue by SamyBencherif** [segao/PyPaint#1]
Hello! I'm looking to build upon this project. Currently it looks like a folder of images might be missing from the repo.

My goal is to attempt to tune things towards the OG ms paint (XP version) which I have on my macbook running on Wine (out of love).

I am also intrigued with shoehorning in some animation features. Not that this matters really. My two "issues" are how should I deal with the missing assets (make them myself?) and may I use this project? (there's no license)

**Comment by segao** [comment]
Hello!

I dug into my old computer and uploaded a folder of the assets. Hopefully that helps! Feel free to do whatever with it, this was definitely a throwaway project that I was actually looking to delete soon haha :)

- Sharon Gao

**Comment by SamyBencherif** [comment]
Thanks for doing that. I'm also working on a theme that matches the windows XP iconography.

<img width="186" alt="Screen Shot 2019-04-23 at 11 49 01 AM" src="https://user-images.githubusercontent.com/10871454/56596054-cfbcec00-65bd-11e9-96e2-d8cff1c2cb6e.png">

By the way, congratulations, your "throwaway" project is by far the best tkinter paint project on github 🥇💯
